controllers/StoreController.php
<?php
if (!isset($_SESSION)) { session_start(); }

class StoreController extends CController
{
	public $layout='store_tpl';	
	public $crumbsTitle='';
	public $theme_compression='';
	
	public function beforeAction($action)
	{
		//$cs->registerCssFile($baseUrl.'/css/yourcss.css'); 		
		if( parent::beforeAction($action) ) {			
			
			/** Register all scripts here*/
			if ($this->theme_compression==2){
				ScriptManagerCompress::RegisterAllJSFile();
			    ScriptManagerCompress::registerAllCSSFiles();
			   
				$compress_css = require_once 'assets/css/css.php';
			    $cs = Yii::app()->getClientScript();
			    Yii::app()->clientScript->registerCss('compress-css',$compress_css);
			} else {
			   ScriptManager::RegisterAllJSFile();
			   ScriptManager::registerAllCSSFiles();
			}
			return true;
		}
		return false;
	}
	
	public function accessRules()
	{		
		
	}
	
    public function filters()
    {
    	$this->theme_compression = getOptionA('theme_compression');
		if ($this->theme_compression==2){
	        $filters = array(  
	            array(
	                'application.filters.HtmlCompressorFilter',
	            ),  
	        );
	        return $filters;
		}
    }	
		
	public function init()
	{		
		 $name=Yii::app()->functions->getOptionAdmin('website_title');
		 if (!empty($name)){		 	
		 	 Yii::app()->name = $name;
		 }
		 		 
		 // set website timezone
		 $website_timezone=Yii::app()->functions->getOptionAdmin("website_timezone");		 
		 if (!empty($website_timezone)){		 	
		 	Yii::app()->timeZone=$website_timezone;
		 }		 		 
	}
	
	public function actionHome()
	{
		
		unset($_SESSION['voucher_code']);
        unset($_SESSION['less_voucher']);
        unset($_SESSION['google_http_refferer']); 
        
		if (isset($_GET['token'])){
			if (!empty($_GET['token'])){
			    //Yii::app()->functions->paypalSetCancelOrder($_GET['token']);
			}
		}
				
		$seo_title=Yii::app()->functions->getOptionAdmin('seo_home');
		$seo_meta=Yii::app()->functions->getOptionAdmin('seo_home_meta');
		$seo_key=Yii::app()->functions->getOptionAdmin('seo_home_keywords');
					
		if (!empty($seo_title)){
		   $seo_title=smarty('website_title',getWebsiteName(),$seo_title);
		   $this->pageTitle=$seo_title;
		   Yii::app()->functions->setSEO($seo_title,$seo_meta,$seo_key);
		}

		
		$this->render('index',array(
		   'home_search_mode'=>getOptionA('home_search_mode'),
		   'enabled_advance_search'=> getOptionA('enabled_advance_search'),
		   'theme_hide_how_works'=>getOptionA('theme_hide_how_works'),
		   'theme_hide_cuisine'=>getOptionA('theme_hide_cuisine'),
		   'disabled_featured_merchant'=>getOptionA('disabled_featured_merchant'),
		   'disabled_subscription'=>getOptionA('disabled_subscription'),
		   'theme_show_app'=>getOptionA('theme_show_app'),
		   'theme_app_android'=>FunctionsV3::prettyUrl(getOptionA('theme_app_android')),
		   'theme_app_ios'=>FunctionsV3::prettyUrl(getOptionA('theme_app_ios')),
		   'theme_app_windows'=>FunctionsV3::prettyUrl(getOptionA('theme_app_windows')),
		));
	}
				  
	public function actionIndex()
	{							
		$this->redirect(Yii::app()->request->baseUrl."/store/home");
		Yii::app()->end();		
	}	
	
	public function actionCuisine()
	{
		/*update merchant if expired and sponsored*/
		Yii::app()->functions->updateMerchantSponsored();
		Yii::app()->functions->updateMerchantExpired();
		
		/*$category='';
		$getdata=isset($_GET)?$_GET:'';
		if(is_array($getdata) && count($getdata)>=1){
			$category=$getdata['category'];
			$category=str_replace("-"," ",$category);
		}
		
		if ( $cat_res=Yii::app()->functions->GetCuisineByName($category)){
			$cuisine_id=$cat_res['cuisine_id'];
		 } else $cuisine_id="-1";
		 $filter_cuisine[]=$cuisine_id;*/
		
		$cuisine_id=isset($_GET['category'])?$_GET['category']:'';
		 
		 if (!isset($_GET['filter_cuisine'])){
		 	$_GET['filter_cuisine']='';
		 }
		 
		$_GET['filter_cuisine']=$_GET['filter_cuisine'].",$cuisine_id";
		 			 
	    $res=FunctionsV3::searchByMerchant(
		   'kr_search_category',
		   isset($_GET['st'])?$_GET['st']:'',
		   isset($_GET['page'])?$_GET['page']:0,
		   FunctionsV3::getPerPage(),
		   $_GET			  
		);
		
		$country_list=Yii::app()->functions->CountryList();
		$country=getOptionA('merchant_default_country');  
		if (array_key_exists($country,(array)$country_list)){
			$country_name = $country_list[$country];
		} else $country_name="United states";
				
		if ($lat_res=Yii::app()->functions->geodecodeAddress($country_name)){    		
    		$lat_res=array(
    		  'lat'=>$lat_res['lat'],
    		  'lng'=>$lat_res['long'],
    		);
    	} else {
    		$lat_res=array();
    	} 
    	
    	$cs = Yii::app()->getClientScript();
    	$cs->registerScript(
		  'country_coordinates',
		  'var country_coordinates = '.json_encode($lat_res).'
		  ',
		  CClientScript::POS_HEAD
		);
		
		$this->render('merchant-list-cuisine',array(
		  'list'=>$res,
		  'category'=>$category
		));
	}
	
	public function actionSignup()
	{
		$cs = Yii::app()->getClientScript();
		$baseUrl = Yii::app()->baseUrl; 
		$cs->registerScriptFile($baseUrl."/assets/js/fblogin.js?ver=1"); 
		    
		if (Yii::app()->functions->isClientLogin()){
			$this->redirect(Yii::app()->createUrl('/store')); 
			die();
		}
		
		$act_menu=FunctionsV3::getTopMenuActivated();
		if (!in_array('signup',(array)$act_menu)){
			$this->render('404-page',array('header'=>true));
			return ;
		}	
		
		$fb=1;
		$fb_app_id=getOptionA('fb_app_id');
		$fb_flag=getOptionA('fb_flag');
		
		if ( $fb_flag=="" && $fb_app_id<>""){
			$fb=2;
		}
		
		$this->render('signup',array(
		   'terms_customer'=>getOptionA('website_terms_customer'),
		   'terms_customer_url'=>Yii::app()->functions->prettyLink(getOptionA('website_terms_customer_url')),
		   'fb_flag'=>$fb,
		   'google_login_enabled'=>getOptionA('google_login_enabled'),
		   'captcha_customer_login'=>getOptionA('captcha_customer_login'),
		   'captcha_customer_signup'=>getOptionA('captcha_customer_signup')
		));
	}
	
	public function actionSignin()
	{
		$this->render('index');
	}
	
	public function actionMerchantSignup()
	{		
		
		$act_menu=FunctionsV3::getTopMenuActivated();
		if (!in_array('resto_signup',(array)$act_menu)){
			$this->render('404-page',array('header'=>true));
			return ;
		}
		
		$seo_title=Yii::app()->functions->getOptionAdmin('seo_merchantsignup');
		$seo_meta=Yii::app()->functions->getOptionAdmin('seo_merchantsignup_meta');
		$seo_key=Yii::app()->functions->getOptionAdmin('seo_merchantsignup_keywords');
		
		if (!empty($seo_title)){
		   $seo_title=smarty('website_title',getWebsiteName(),$seo_title);
		   $this->pageTitle=$seo_title;
		   Yii::app()->functions->setSEO($seo_title,$seo_meta,$seo_key);
		}
		
		if(isset($_GET['package_id'])){
			$_GET['id']=$_GET['package_id'];
		}	
		
		if (isset($_GET['Do'])){
			$_GET['do']=$_GET['Do'];
		}	
		
		if (isset($_GET['do'])){
			switch ($_GET['do']) {
				case 'step2':
					$this->render('merchant-signup-step2',array(
					  'data'=>Yii::app()->functions->getPackagesById($_GET['package_id']),
					  'limit_post'=>Yii::app()->functions->ListlimitedPost(),
					  'terms_merchant'=>getOptionA('website_terms_merchant'),
					  'terms_merchant_url'=>getOptionA('website_terms_merchant_url'),
					  'package_list'=>Yii::app()->functions->getPackagesList(),
					  'kapcha_enabled'=>getOptionA('captcha_merchant_signup')
					));		
					break;
				case "step3":
					 $renew=false;
					 $package_id=isset($_GET['package_id'])?$_GET['package_id']:'';  
					 if (isset($_GET['action'])){	 
						 $renew=true;
					 } 
					 $this->render('merchant-signup-step3',array(
					    'merchant'=>Yii::app()->functions->getMerchantByToken($_GET['token']),
					    'package_id'=>$package_id,
					    'renew'=>$renew					    
					 ));		
					break;
				case "step3a":
					 $this->render('merchant-signup-step3a');		
					break;	
				case "step3b":					    
					if (isset($_GET['gateway'])){
						if ($_GET['gateway']=="mcd"){
							$this->render('mercado-init');
						} elseif ( $_GET['gateway']=="pyl" ){
							$this->render('payline-init2');
						} elseif ( $_GET['gateway']=="ide" ){
							$this->render('sow-init');
						} elseif ( $_GET['gateway']=="payu" ){							
							$this->render('pau-init');	
						} elseif ( $_GET['gateway']=="pys" ){							
							$this->render('paysera-init');	
						} else {
							$this->render($_GET['gateway'].'-init');	
						}
					} else $this->render('merchant-signup-step3b');
					break;		
					
				case "step4":					     
				     $disabled_verification=Yii::app()->functions->getOptionAdmin('merchant_email_verification');
				     if ( $disabled_verification=="yes"){
				     	$this->render('merchant-signup-thankyou2',array(
				     	  'data'=>Yii::app()->functions->getMerchantByToken($_GET['token'])
				     	));		
				     } else {			
				     					     	
				     	 $continue=true;
						 if ($merchant=Yii::app()->functions->getMerchantByToken($_GET['token'])){	
							if ( $merchant['package_price']>=1){
								if ($merchant['payment_steps']!=3){
									$continue=false;
								}
							}
						 } else $continue=false;
						 						 						
				     	 /*check if payment was offline*/
				     	 $is_offline_paid=false;
			      	 	 if ( $package_info=FunctionsV3::getMerchantPaymentMembership($merchant['merchant_id'],
			      	 	 $merchant['package_id'])){						      	 	 	  	 	
			      	 		$offline_payment=FunctionsV3::getOfflinePaymentList();			      	 		
			      	 		if ( array_key_exists($package_info['payment_type'],(array)$offline_payment)){
			      	 			$is_offline_paid=true;
			      	 		}
			      	 	 }			

			      	 	 if ($is_offline_paid){
			      	 	 	$this->render('merchant-signup-thankyou2',array(
				     	       'data'=>$merchant
				     	    ));		
			      	 	 } else {				   			      	 	   		     						 
					     	 $this->render('merchant-signup-step4',array(
					            'continue'=>$continue
					         ));						
			      	 	 }	 
				     }
					break;	

views/layouts/_store.php
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<!--[if lt IE 7 ]><html class="ie ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]><html class="ie ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]><html class="ie ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!-->
<html lang="en">
<head>

<!-- IE6-8 support of HTML5 elements --> 
<!--[if lt IE 9]>
<script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

<!--[if IE]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script><![endif]-->
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta name="viewport" content="width=device-width" />
<title><?php echo CHtml::encode($this->pageTitle); ?></title>
<link rel="shortcut icon" href="<?php echo  Yii::app()->request->baseUrl; ?>/favicon.ico?ver=1.0" />
<?php Widgets::analyticsCode();?>
</head>
<body>
<div class="content">
 <?php echo $content;?>
</div> <!--END content-->
<div class="footer-wrap" style="display:none;"></div>
<?php ScriptManager::registerGlobalVariables();?>
</body>
</html>

views/layouts/front_bottom_footer.php
<?php

if (!Yii::app()->functions->isClientLogin()){
?>
<!-- Login modal -->   
<div class="modal fade" id="login_2" tabindex="-1" role="dialog" aria-labelledby="myLogin" aria-hidden="true">
		<div class="modal-dialog">
			<div class="modal-content modal-popup"> 
				<a href="#" class="close-link"><i class="icon_close_alt2"></i></a>
				<form action="" method="post" class="popup-form forms has-validation-callback lform" id="forms-login">
				<input id="action" type="hidden" name="action" value="clientLogin">
				<input id="currentController" type="hidden" name="currentController" value="store">
                	<div class="login_icon"><i class="icon_lock_alt"></i></div>
					<input id="username1" type="text" required="1" class="form-control form-white" name="username" placeholder="Username">
					<input id="password1" type="password" required="1" class="form-control form-white" name="password" placeholder="Password">
					<div class="text-left">
						<a onclick="changeForm(2)" href="javascript:;" >Forgot Password?</a>
					</div>
					<button type="submit" class="btn btn-submit">Login</button>  
				</form>
				
				<form action="" onsubmit="return false;" method="post" class="popup-form ffrom frm-modal-forgotpass has-validation-callback" id="frm-modal-forgotpass" style="display:none;">
					<div class="login_icon"><i class="icon_lock_alt"></i></div>
					<input id="action" type="hidden" name="action" value="forgotPassword">
					<input id="do-action" type="hidden" name="do-action" value="">
					<input id="username-email" type="text" required="1" class="form-control form-white" name="username-email" placeholder="Email address">
					<div class="text-left">
							<a onclick="changeForm(1)" href="javascript:;" >Click for Login</a>
						</div>
					<button type="submit" class="btn btn-submit">Retrieve Password</button>
				</form>
			</div>
		</div>
	</div><!-- End modal -->   
	 
	
	<script>
	function changeForm(mode){
		// alert(mode);
		if(mode == 1)
		{
			jQuery(".lform").css("display","block");
			jQuery("#frm-modal-forgotpass").css("display","none");
		
		}else
		{
			jQuery(".lform").css("display","none");
			jQuery("#frm-modal-forgotpass").css("display","block");
		}
	}
	</script>
	

	
	
	
    
<!-- Register modal -->   
<div class="modal fade" id="register" tabindex="-1" role="dialog" aria-labelledby="myRegister" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content modal-popup">
			<a href="#" class="close-link"><i class="icon_close_alt2"></i></a>
			<form action="#" class="popup-form" id="myRegister">
				<div class="login_icon"><i class="icon_lock_alt"></i></div>
				<input type="text" class="form-control form-white" placeholder="Name">
				<input type="text" class="form-control form-white" placeholder="Last Name">
				<input type="email" class="form-control form-white" placeholder="Email">
				<input type="text" class="form-control form-white" placeholder="Password"  id="password1">
				<input type="text" class="form-control form-white" placeholder="Confirm password"  id="password2">
				<div id="pass-info" class="clearfix"></div>
				<div class="checkbox-holder text-left">
					<div class="checkbox">
						<input type="checkbox" value="accept_2" id="check_2" name="check_2" />
						<label for="check_2"><span>I Agree to the <strong>Terms &amp; Conditions</strong></span></label>
					</div>
				</div>
				<button type="submit" class="btn btn-submit">Register</button>
			</form>
		</div>
	</div>
</div><!-- End Register modal --><!--[if lte IE 8]>
	<p class="chromeframe">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a>.</p>
<![endif]-->
   <?php
}
?>   
    <!-- Footer ================================================== -->
    <footer>
    <div class="container">
        <div class="row">
            <div class="col-md-4 col-sm-3">
			<h3>Secure payments by yoPay®</h3>
			<p>
			<img class="img-responsive" alt="" src="<?php echo assetsURL()?>/img/cards.png">
			</p>
			
                <p>
                    <?php FunctionsV3::getFooterAddress();?>
                </p>
            </div>
            <div class="col-md-3 col-sm-3">
				<?php if ($theme_hide_footer_section1!=2):?>
				   <h3><?php 
				   
				   
				   
				   
				   echo t("Menu")?></h3>
				  
				   <?php if (is_array($menu) && count($menu)>=1):?>
				   <?php foreach ($menu as $val): ?>
				   <li>
					 <a 
					   href="<?php echo FunctionsV3::customPageUrlNew($val)?>" <?php FunctionsV3::openAsNewTab($val)?> >
					  <?php echo $val['page_name']?></a>
				   </li>
				   <?php endforeach;?>
				   <li><a href="<?php echo Yii::app()->createUrl('/store/contact')?>" >Contacts</a></li>
				   <li><a href="<?php echo Yii::app()->createUrl('/store/signup')?>" >Login</a></li>
				   <li><a href="<?php echo Yii::app()->createUrl('/store/signup')?>" >Register</a></li>
				   <?php endif;?>
				   
				   <?php endif;?>
				
				
				<?php if ($theme_hide_footer_section2!=2):?>
				 <h3><?php echo t("Others")?></h3>
				 
				   <?php if (is_array($others_menu) && count($others_menu)>=1):?>
				   <?php foreach ($others_menu as $val):?>
				   <li>
					 <a 
					   href="<?php echo FunctionsV3::customPageUrl($val)?>" <?php FunctionsV3::openAsNewTab($val)?> >
					  <?php echo $val['page_name']?></a>
				   </li>
				   <?php endforeach;?>
				   <?php endif;?>
				 
				 <?php endif;?> 
            </div>
            <div class="col-md-3 col-sm-3" id="newsletter">
				<?php if ( getOptionA('disabled_subscription') == ""):?>
                <h3>Newsletter</h3>
                <p><?php echo t("Subscribe to our newsletter") ?></p>
                <div id="message-newsletter_2">
                </div>
				<form method="POST" id="frm-subscribe" class="frm-subscribe" onsubmit="return false;">
				<?php echo CHtml::hiddenField('action','subscribeNewsletter')?>
					<div class="form-group">
						<?php echo CHtml::textField('subscriber_email','',array(
								 'placeholder'=>t("E-mail"),
								 'required'=>true,
								 'class'=>"email form-control"
							   ))?>
					</div>
					<button class="btn_1"><?php echo t("Subscribe")?> </button>
				</form>
				<?php endif;?>				
            </div>
            <div class="col-md-2 col-sm-3">
                 <?php 
					if ($show_language<>1){
						echo '<h3>Settings</h3>';
						if ( $theme_lang_pos=="bottom" || $theme_lang_pos==""){
							echo CHtml::dropDownList('language-options','',
							 (array)FunctionsV3::getLanguage()
							 ,array(
							 'class'=>"language-options selectpicker",
							 'title'=>t("Select language")
							));
						}
					}
				?>
            </div>
        </div><!-- End row -->
		
		 <?php if ($social_flag<>1):?>
        <div class="row">
            <div class="col-md-12">
                <div id="social_footer">
                    <ul>
                        <?php if (!empty($fb_page)):?>
							<li><a href="<?php echo FunctionsV3::prettyUrl($fb_page)?>"><i class="icon-facebook"></i></a></li>
						<?php endif;?>
						<?php if (!empty($twitter_page)):?>
							<li><a href="<?php echo FunctionsV3::prettyUrl($twitter_page)?>"><i class="icon-twitter"></i></a></li>
						<?php endif;?>
						<?php if (!empty($google_page)):?>
							<li><a href="<?php echo FunctionsV3::prettyUrl($google_page)?>"><i class="icon-google"></i></a></li>
						<?php endif;?>
						<?php if (!empty($intagram_page)):?>
							<li><a href="<?php echo FunctionsV3::prettyUrl($intagram_page)?>"><i class="icon-instagram"></i></a></li>
						<?php endif;?>
						<?php if (!empty($youtube_url)):?>
							<li><a href="<?php echo FunctionsV3::prettyUrl($youtube_url)?>"><i class="icon-youtube-play"></i></a></li>
						<?php endif;?>
                    </ul>
                    <p>
                        © Zen Deliver <?php echo date("Y"); ?>
                    </p>
                </div>
            </div>
        </div><!-- End row -->
		<?php endif;?>
    </div><!-- End container -->
    </footer>
    <!-- End Footer =============================================== -->
	
	
	
	
	
	

views/layouts/front_footer.php
<?php 
/*add global variables to footer*/
ScriptManager::registerGlobalVariables();
?>
<script src="//www.google.com/recaptcha/api.js?onload=onloadMyCallback&render=explicit" async defer ></script>
</body>
</html>

views/layouts/front_header.php
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<!--[if lt IE 7 ]><html class="ie ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]><html class="ie ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]><html class="ie ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!-->
<html lang="en">
<head>

<!-- IE6-8 support of HTML5 elements --> 
<!--[if lt IE 9]>
<script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

<!--[if IE]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script><![endif]-->
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
<title><?php echo CHtml::encode($this->pageTitle); ?></title>
<link rel="shortcut icon" href="<?php echo  Yii::app()->request->baseUrl; ?>/favicon.ico?ver=1.1" />
<?php 
/*add the analytic codes */
Widgets::analyticsCode();
?>
</head>
<body>

views/layouts/front_top_menu.php
	
<div class="layer"></div><!-- Mobile menu overlay mask -->

    <div id="preloader">
        <div class="sk-spinner sk-spinner-wave" id="status">
            <div class="sk-rect1"></div>
            <div class="sk-rect2"></div>
            <div class="sk-rect3"></div>
            <div class="sk-rect4"></div>
            <div class="sk-rect5"></div>
        </div>
    </div><!-- End Preload -->
    
    <!-- Header   -->
    <header>
    <div class="container-fluid">
        <div class="row">
            <div class="col--md-4 col-sm-4 col-xs-4">
				<?php if ( $theme_hide_logo<>2):?>
					<a href="<?php echo Yii::app()->createUrl('/store')?>"  id="logo">
					 <img src="<?php echo FunctionsV3::getDesktopLogo();?>" style="margin-top: -6px;"  width="190" height="23" alt="" data-retina="true" class="hidden-xs">
					 <img src="<?php echo FunctionsV3::getMobileLogo();?>" style="margin-top: -6px;"  width="59" height="23" alt="" data-retina="true" class="hidden-lg hidden-md hidden-sm">
					</a>
				<?php endif;?>
            </div>
            <nav class="col--md-8 col-sm-8 col-xs-8">
            <a class="cmn-toggle-switch cmn-toggle-switch__htx open_close" href="javascript:void(0);"><span>Menu mobile</span></a>
            <div class="main-menu">
                <div id="header_menu">
                    <img src="<?php echo FunctionsV3::getDesktopLogo();?>" width="190" height="23" alt="" data-retina="true">
                </div>
                <a href="#" class="open_close" id="close_in"><i class="icon_close"></i></a>
                <?php $this->widget('zii.widgets.CMenu', FunctionsV3::getMenu('') );?> 
            </div><!-- End main-menu -->
            </nav>
        </div><!-- End row -->
    </div><!-- End container -->
    </header>
	<!-- End Header =============================================== -->
	<?php
	/*
	
<div class="top-menu-wrapper <?php echo "top-".$action;?>">

<div class="container border" >
  <div class="col-md-3 col-xs-3 border col-a">
    <?php if ( $theme_hide_logo<>2):?>
    <a href="<?php echo Yii::app()->createUrl('/store')?>">
     <img src="<?php echo FunctionsV3::getDesktopLogo();?>" class="logo logo-desktop">
     <img src="<?php echo FunctionsV3::getMobileLogo();?>" class="logo logo-mobile">
    </a>
    <?php endif;?>
  </div>
  
  <div class="col-xs-1 menu-nav-mobile border relative">
     <a href="#"><i class="ion-android-menu"></i></a>
  </div> <!--menu-nav-mobile-->
  
  <?php if ( Yii::app()->controller->action->id =="menu"):?>
  <div class="col-xs-1 cart-mobile-handle border relative">
     <a href="javascript:;"><i class="ion-ios-cart"></i></a>
  </div> <!--cart-mobile-handle-->
  <?php endif;?>
  
  
  <div class="col-md-9 border col-b">
    <?php $this->widget('zii.widgets.CMenu', FunctionsV3::getMenu() );?> 
    <div class="clear"></div>
  </div>
  
</div> <!--container-->

</div> <!--END top-menu-->

<div class="menu-top-menu">
    <?php $this->widget('zii.widgets.CMenu', FunctionsV3::getMenu('mobile-menu') );?> 
    <div class="clear"></div>
</div> <!--menu-top-menu-->
*/
?>

views/layouts/mobile_tpl.php
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<!--[if lt IE 7 ]><html class="ie ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]><html class="ie ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]><html class="ie ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!-->
<html lang="en">
<head>

<!-- IE6-8 support of HTML5 elements --> 
<!--[if lt IE 9]>
<script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

<!--[if IE]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script><![endif]-->
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
<title><?php echo CHtml::encode($this->pageTitle); ?></title>
<link rel="shortcut icon" href="<?php echo  Yii::app()->request->baseUrl; ?>/favicon.ico?ver=1.1" />
<?php 
/*add the analytic codes */
Widgets::analyticsCode();
?>
</head>
<body>
<?php echo $content;?>
</body>
</html>